#!/bin/bash

# Hack to ensure that if we are running on OS X with a homebrew installed
# GNU sed then we can still run sed.
runsed() {
  if hash gsed 2>/dev/null; then
    gsed "$@"
  else
    sed "$@"
  fi
}

git clone https://github.com/openconfig/public.git
mkdir deps
cp ./public/third_party/ietf/{ietf,iana}* deps
echo "Generate yang models in Go"
GO111MODULE=on go run $GOPATH/src/github.com/openconfig/ygot/generator/generator.go -path=public,deps -output_file=modeldata/oc/oc.go \
  -package_name=oc -generate_fakeroot -fakeroot_name=device -compress_paths=true \
  -exclude_modules=ietf-interfaces \
  -generate_rename \
  -generate_append \
  -generate_getters \
  -generate_leaf_getters \
  -annotations \
  public/release/models/platform/openconfig-platform-transceiver.yang \
  public/release/models/lacp/openconfig-lacp.yang \
  public/release/models/lldp/openconfig-lldp.yang \
  public/release/models/stp/openconfig-spanning-tree.yang \
  public/release/models/interfaces/openconfig-interfaces.yang \
  public/release/models/interfaces/openconfig-if-ip.yang \
  public/release/models/interfaces/openconfig-if-aggregate.yang \
  public/release/models/interfaces/openconfig-if-ethernet.yang \
  public/release/models/interfaces/openconfig-if-ip-ext.yang
echo "Make header note"
# runsed -i 's/This package was generated by.*/NOTE WELL: This is an example code file that is distributed with ygot.\nIt should not be used within your application, as it WILL change,\nwithout warning. Rather, you should generate structs directly from\nOpenConfig models using the ygot package.\n\nThis package was generated by github.com\/openconfig\/ygot/g' oc.go
echo "Format Go source code"
gofmt -w -s modeldata/oc/oc.go
echo "Remove dependencies"
rm -rf deps public
