// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ocproto/openconfig/openconfig_lldp/openconfig_lldp.proto

package openconfig_openconfig_lldp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/openconfig/ygot/proto/yext"
	ywrapper "github.com/openconfig/ygot/proto/ywrapper"
	math "math"
	enums "openconfig/enums"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Lldp struct {
	Config               *Lldp_Config     `protobuf:"bytes,445759159,opt,name=config,proto3" json:"config,omitempty"`
	Interfaces           *Lldp_Interfaces `protobuf:"bytes,1547797,opt,name=interfaces,proto3" json:"interfaces,omitempty"`
	State                *Lldp_State      `protobuf:"bytes,172892392,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Lldp) Reset()         { *m = Lldp{} }
func (m *Lldp) String() string { return proto.CompactTextString(m) }
func (*Lldp) ProtoMessage()    {}
func (*Lldp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0}
}

func (m *Lldp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp.Unmarshal(m, b)
}
func (m *Lldp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp.Marshal(b, m, deterministic)
}
func (m *Lldp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp.Merge(m, src)
}
func (m *Lldp) XXX_Size() int {
	return xxx_messageInfo_Lldp.Size(m)
}
func (m *Lldp) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp proto.InternalMessageInfo

func (m *Lldp) GetConfig() *Lldp_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Lldp) GetInterfaces() *Lldp_Interfaces {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

func (m *Lldp) GetState() *Lldp_State {
	if m != nil {
		return m.State
	}
	return nil
}

type Lldp_Config struct {
	ChassisId                *ywrapper.StringValue              `protobuf:"bytes,508074652,opt,name=chassis_id,json=chassisId,proto3" json:"chassis_id,omitempty"`
	ChassisIdType            enums.OpenconfigLldpChassisIdType  `protobuf:"varint,298922545,opt,name=chassis_id_type,json=chassisIdType,proto3,enum=openconfig.enums.OpenconfigLldpChassisIdType" json:"chassis_id_type,omitempty"`
	Enabled                  *ywrapper.BoolValue                `protobuf:"bytes,106066121,opt,name=enabled,proto3" json:"enabled,omitempty"`
	HelloTimer               *ywrapper.UintValue                `protobuf:"bytes,499388674,opt,name=hello_timer,json=helloTimer,proto3" json:"hello_timer,omitempty"`
	SuppressTlvAdvertisement []enums.OpenconfigLldpTypesLLDPTLV `protobuf:"varint,105840670,rep,packed,name=suppress_tlv_advertisement,json=suppressTlvAdvertisement,proto3,enum=openconfig.enums.OpenconfigLldpTypesLLDPTLV" json:"suppress_tlv_advertisement,omitempty"`
	SystemDescription        *ywrapper.StringValue              `protobuf:"bytes,410395368,opt,name=system_description,json=systemDescription,proto3" json:"system_description,omitempty"`
	SystemName               *ywrapper.StringValue              `protobuf:"bytes,20955911,opt,name=system_name,json=systemName,proto3" json:"system_name,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                           `json:"-"`
	XXX_unrecognized         []byte                             `json:"-"`
	XXX_sizecache            int32                              `json:"-"`
}

func (m *Lldp_Config) Reset()         { *m = Lldp_Config{} }
func (m *Lldp_Config) String() string { return proto.CompactTextString(m) }
func (*Lldp_Config) ProtoMessage()    {}
func (*Lldp_Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 0}
}

func (m *Lldp_Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_Config.Unmarshal(m, b)
}
func (m *Lldp_Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_Config.Marshal(b, m, deterministic)
}
func (m *Lldp_Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_Config.Merge(m, src)
}
func (m *Lldp_Config) XXX_Size() int {
	return xxx_messageInfo_Lldp_Config.Size(m)
}
func (m *Lldp_Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_Config proto.InternalMessageInfo

func (m *Lldp_Config) GetChassisId() *ywrapper.StringValue {
	if m != nil {
		return m.ChassisId
	}
	return nil
}

func (m *Lldp_Config) GetChassisIdType() enums.OpenconfigLldpChassisIdType {
	if m != nil {
		return m.ChassisIdType
	}
	return enums.OpenconfigLldpChassisIdType_OPENCONFIGLLDPCHASSISIDTYPE_UNSET
}

func (m *Lldp_Config) GetEnabled() *ywrapper.BoolValue {
	if m != nil {
		return m.Enabled
	}
	return nil
}

func (m *Lldp_Config) GetHelloTimer() *ywrapper.UintValue {
	if m != nil {
		return m.HelloTimer
	}
	return nil
}

func (m *Lldp_Config) GetSuppressTlvAdvertisement() []enums.OpenconfigLldpTypesLLDPTLV {
	if m != nil {
		return m.SuppressTlvAdvertisement
	}
	return nil
}

func (m *Lldp_Config) GetSystemDescription() *ywrapper.StringValue {
	if m != nil {
		return m.SystemDescription
	}
	return nil
}

func (m *Lldp_Config) GetSystemName() *ywrapper.StringValue {
	if m != nil {
		return m.SystemName
	}
	return nil
}

type Lldp_Interfaces struct {
	Interface            []*Lldp_Interfaces_InterfaceKey `protobuf:"bytes,393279601,rep,name=interface,proto3" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *Lldp_Interfaces) Reset()         { *m = Lldp_Interfaces{} }
func (m *Lldp_Interfaces) String() string { return proto.CompactTextString(m) }
func (*Lldp_Interfaces) ProtoMessage()    {}
func (*Lldp_Interfaces) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 1}
}

func (m *Lldp_Interfaces) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_Interfaces.Unmarshal(m, b)
}
func (m *Lldp_Interfaces) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_Interfaces.Marshal(b, m, deterministic)
}
func (m *Lldp_Interfaces) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_Interfaces.Merge(m, src)
}
func (m *Lldp_Interfaces) XXX_Size() int {
	return xxx_messageInfo_Lldp_Interfaces.Size(m)
}
func (m *Lldp_Interfaces) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_Interfaces.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_Interfaces proto.InternalMessageInfo

func (m *Lldp_Interfaces) GetInterface() []*Lldp_Interfaces_InterfaceKey {
	if m != nil {
		return m.Interface
	}
	return nil
}

type Lldp_Interfaces_Interface struct {
	Config               *Lldp_Interfaces_Interface_Config    `protobuf:"bytes,28424342,opt,name=config,proto3" json:"config,omitempty"`
	Neighbors            *Lldp_Interfaces_Interface_Neighbors `protobuf:"bytes,513860845,opt,name=neighbors,proto3" json:"neighbors,omitempty"`
	State                *Lldp_Interfaces_Interface_State     `protobuf:"bytes,205931331,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *Lldp_Interfaces_Interface) Reset()         { *m = Lldp_Interfaces_Interface{} }
func (m *Lldp_Interfaces_Interface) String() string { return proto.CompactTextString(m) }
func (*Lldp_Interfaces_Interface) ProtoMessage()    {}
func (*Lldp_Interfaces_Interface) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 1, 0}
}

func (m *Lldp_Interfaces_Interface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_Interfaces_Interface.Unmarshal(m, b)
}
func (m *Lldp_Interfaces_Interface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_Interfaces_Interface.Marshal(b, m, deterministic)
}
func (m *Lldp_Interfaces_Interface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_Interfaces_Interface.Merge(m, src)
}
func (m *Lldp_Interfaces_Interface) XXX_Size() int {
	return xxx_messageInfo_Lldp_Interfaces_Interface.Size(m)
}
func (m *Lldp_Interfaces_Interface) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_Interfaces_Interface.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_Interfaces_Interface proto.InternalMessageInfo

func (m *Lldp_Interfaces_Interface) GetConfig() *Lldp_Interfaces_Interface_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Lldp_Interfaces_Interface) GetNeighbors() *Lldp_Interfaces_Interface_Neighbors {
	if m != nil {
		return m.Neighbors
	}
	return nil
}

func (m *Lldp_Interfaces_Interface) GetState() *Lldp_Interfaces_Interface_State {
	if m != nil {
		return m.State
	}
	return nil
}

type Lldp_Interfaces_Interface_Config struct {
	Enabled              *ywrapper.BoolValue   `protobuf:"bytes,509689348,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Name                 *ywrapper.StringValue `protobuf:"bytes,79832956,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Lldp_Interfaces_Interface_Config) Reset()         { *m = Lldp_Interfaces_Interface_Config{} }
func (m *Lldp_Interfaces_Interface_Config) String() string { return proto.CompactTextString(m) }
func (*Lldp_Interfaces_Interface_Config) ProtoMessage()    {}
func (*Lldp_Interfaces_Interface_Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 1, 0, 0}
}

func (m *Lldp_Interfaces_Interface_Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Config.Unmarshal(m, b)
}
func (m *Lldp_Interfaces_Interface_Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Config.Marshal(b, m, deterministic)
}
func (m *Lldp_Interfaces_Interface_Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_Interfaces_Interface_Config.Merge(m, src)
}
func (m *Lldp_Interfaces_Interface_Config) XXX_Size() int {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Config.Size(m)
}
func (m *Lldp_Interfaces_Interface_Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_Interfaces_Interface_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_Interfaces_Interface_Config proto.InternalMessageInfo

func (m *Lldp_Interfaces_Interface_Config) GetEnabled() *ywrapper.BoolValue {
	if m != nil {
		return m.Enabled
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_Config) GetName() *ywrapper.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

type Lldp_Interfaces_Interface_Neighbors struct {
	Neighbor             []*Lldp_Interfaces_Interface_Neighbors_NeighborKey `protobuf:"bytes,518660342,rep,name=neighbor,proto3" json:"neighbor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *Lldp_Interfaces_Interface_Neighbors) Reset()         { *m = Lldp_Interfaces_Interface_Neighbors{} }
func (m *Lldp_Interfaces_Interface_Neighbors) String() string { return proto.CompactTextString(m) }
func (*Lldp_Interfaces_Interface_Neighbors) ProtoMessage()    {}
func (*Lldp_Interfaces_Interface_Neighbors) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 1, 0, 1}
}

func (m *Lldp_Interfaces_Interface_Neighbors) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors.Unmarshal(m, b)
}
func (m *Lldp_Interfaces_Interface_Neighbors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors.Marshal(b, m, deterministic)
}
func (m *Lldp_Interfaces_Interface_Neighbors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors.Merge(m, src)
}
func (m *Lldp_Interfaces_Interface_Neighbors) XXX_Size() int {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors.Size(m)
}
func (m *Lldp_Interfaces_Interface_Neighbors) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors proto.InternalMessageInfo

func (m *Lldp_Interfaces_Interface_Neighbors) GetNeighbor() []*Lldp_Interfaces_Interface_Neighbors_NeighborKey {
	if m != nil {
		return m.Neighbor
	}
	return nil
}

type Lldp_Interfaces_Interface_Neighbors_Neighbor struct {
	Capabilities         *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities `protobuf:"bytes,457626607,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Config               *Lldp_Interfaces_Interface_Neighbors_Neighbor_Config       `protobuf:"bytes,223570263,opt,name=config,proto3" json:"config,omitempty"`
	CustomTlvs           *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs   `protobuf:"bytes,256243628,opt,name=custom_tlvs,json=customTlvs,proto3" json:"custom_tlvs,omitempty"`
	State                *Lldp_Interfaces_Interface_Neighbors_Neighbor_State        `protobuf:"bytes,43941384,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                   `json:"-"`
	XXX_unrecognized     []byte                                                     `json:"-"`
	XXX_sizecache        int32                                                      `json:"-"`
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor) Reset() {
	*m = Lldp_Interfaces_Interface_Neighbors_Neighbor{}
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor) String() string {
	return proto.CompactTextString(m)
}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor) ProtoMessage() {}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 1, 0, 1, 0}
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor.Unmarshal(m, b)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor.Marshal(b, m, deterministic)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor.Merge(m, src)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor) XXX_Size() int {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor.Size(m)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor proto.InternalMessageInfo

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor) GetCapabilities() *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor) GetConfig() *Lldp_Interfaces_Interface_Neighbors_Neighbor_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor) GetCustomTlvs() *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs {
	if m != nil {
		return m.CustomTlvs
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor) GetState() *Lldp_Interfaces_Interface_Neighbors_Neighbor_State {
	if m != nil {
		return m.State
	}
	return nil
}

type Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities struct {
	Capability           []*Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_CapabilityKey `protobuf:"bytes,233684052,rep,name=capability,proto3" json:"capability,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                                   `json:"-"`
	XXX_unrecognized     []byte                                                                     `json:"-"`
	XXX_sizecache        int32                                                                      `json:"-"`
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities) Reset() {
	*m = Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities{}
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities) String() string {
	return proto.CompactTextString(m)
}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities) ProtoMessage() {}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 1, 0, 1, 0, 0}
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities.Unmarshal(m, b)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities.Marshal(b, m, deterministic)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities.Merge(m, src)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities) XXX_Size() int {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities.Size(m)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities proto.InternalMessageInfo

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities) GetCapability() []*Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_CapabilityKey {
	if m != nil {
		return m.Capability
	}
	return nil
}

type Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability struct {
	Config               *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_Config `protobuf:"bytes,276751961,opt,name=config,proto3" json:"config,omitempty"`
	State                *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_State  `protobuf:"bytes,63273774,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                                     `json:"-"`
	XXX_unrecognized     []byte                                                                       `json:"-"`
	XXX_sizecache        int32                                                                        `json:"-"`
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability) Reset() {
	*m = Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability{}
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability) String() string {
	return proto.CompactTextString(m)
}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability) ProtoMessage() {}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 1, 0, 1, 0, 0, 0}
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability.Unmarshal(m, b)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability.Marshal(b, m, deterministic)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability.Merge(m, src)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability) XXX_Size() int {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability.Size(m)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability proto.InternalMessageInfo

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability) GetConfig() *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability) GetState() *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_State {
	if m != nil {
		return m.State
	}
	return nil
}

type Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_Config struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_Config) Reset() {
	*m = Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_Config{}
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_Config) String() string {
	return proto.CompactTextString(m)
}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_Config) ProtoMessage() {}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 1, 0, 1, 0, 0, 0, 0}
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_Config.Unmarshal(m, b)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_Config.Marshal(b, m, deterministic)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_Config.Merge(m, src)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_Config) XXX_Size() int {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_Config.Size(m)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_Config proto.InternalMessageInfo

type Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_State struct {
	Enabled              *ywrapper.BoolValue                           `protobuf:"bytes,165922252,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Name                 enums.OpenconfigLldpTypesLLDPSYSTEMCAPABILITY `protobuf:"varint,19447668,opt,name=name,proto3,enum=openconfig.enums.OpenconfigLldpTypesLLDPSYSTEMCAPABILITY" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_State) Reset() {
	*m = Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_State{}
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_State) String() string {
	return proto.CompactTextString(m)
}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_State) ProtoMessage() {}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_State) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 1, 0, 1, 0, 0, 0, 1}
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_State.Unmarshal(m, b)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_State.Marshal(b, m, deterministic)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_State.Merge(m, src)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_State) XXX_Size() int {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_State.Size(m)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_State) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_State.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_State proto.InternalMessageInfo

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_State) GetEnabled() *ywrapper.BoolValue {
	if m != nil {
		return m.Enabled
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_State) GetName() enums.OpenconfigLldpTypesLLDPSYSTEMCAPABILITY {
	if m != nil {
		return m.Name
	}
	return enums.OpenconfigLldpTypesLLDPSYSTEMCAPABILITY_OPENCONFIGLLDPTYPESLLDPSYSTEMCAPABILITY_UNSET
}

type Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_CapabilityKey struct {
	Name                 enums.OpenconfigLldpTypesLLDPSYSTEMCAPABILITY                         `protobuf:"varint,1,opt,name=name,proto3,enum=openconfig.enums.OpenconfigLldpTypesLLDPSYSTEMCAPABILITY" json:"name,omitempty"`
	Capability           *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                              `json:"-"`
	XXX_unrecognized     []byte                                                                `json:"-"`
	XXX_sizecache        int32                                                                 `json:"-"`
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_CapabilityKey) Reset() {
	*m = Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_CapabilityKey{}
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_CapabilityKey) String() string {
	return proto.CompactTextString(m)
}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_CapabilityKey) ProtoMessage() {}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_CapabilityKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 1, 0, 1, 0, 0, 1}
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_CapabilityKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_CapabilityKey.Unmarshal(m, b)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_CapabilityKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_CapabilityKey.Marshal(b, m, deterministic)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_CapabilityKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_CapabilityKey.Merge(m, src)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_CapabilityKey) XXX_Size() int {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_CapabilityKey.Size(m)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_CapabilityKey) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_CapabilityKey.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_CapabilityKey proto.InternalMessageInfo

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_CapabilityKey) GetName() enums.OpenconfigLldpTypesLLDPSYSTEMCAPABILITY {
	if m != nil {
		return m.Name
	}
	return enums.OpenconfigLldpTypesLLDPSYSTEMCAPABILITY_OPENCONFIGLLDPTYPESLLDPSYSTEMCAPABILITY_UNSET
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_CapabilityKey) GetCapability() *Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability {
	if m != nil {
		return m.Capability
	}
	return nil
}

type Lldp_Interfaces_Interface_Neighbors_Neighbor_Config struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Config) Reset() {
	*m = Lldp_Interfaces_Interface_Neighbors_Neighbor_Config{}
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Config) String() string {
	return proto.CompactTextString(m)
}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_Config) ProtoMessage() {}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 1, 0, 1, 0, 1}
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Config.Unmarshal(m, b)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Config.Marshal(b, m, deterministic)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Config.Merge(m, src)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Config) XXX_Size() int {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Config.Size(m)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_Config proto.InternalMessageInfo

type Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs struct {
	Tlv                  []*Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey `protobuf:"bytes,222440767,rep,name=tlv,proto3" json:"tlv,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                          `json:"-"`
	XXX_unrecognized     []byte                                                            `json:"-"`
	XXX_sizecache        int32                                                             `json:"-"`
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs) Reset() {
	*m = Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs{}
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs) String() string {
	return proto.CompactTextString(m)
}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs) ProtoMessage() {}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 1, 0, 1, 0, 2}
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs.Unmarshal(m, b)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs.Marshal(b, m, deterministic)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs.Merge(m, src)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs) XXX_Size() int {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs.Size(m)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs proto.InternalMessageInfo

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs) GetTlv() []*Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey {
	if m != nil {
		return m.Tlv
	}
	return nil
}

type Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv struct {
	Config               *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_Config `protobuf:"bytes,228294656,opt,name=config,proto3" json:"config,omitempty"`
	State                *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State  `protobuf:"bytes,100771065,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                            `json:"-"`
	XXX_unrecognized     []byte                                                              `json:"-"`
	XXX_sizecache        int32                                                               `json:"-"`
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv) Reset() {
	*m = Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv{}
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv) String() string {
	return proto.CompactTextString(m)
}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv) ProtoMessage() {}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 1, 0, 1, 0, 2, 0}
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv.Unmarshal(m, b)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv.Marshal(b, m, deterministic)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv.Merge(m, src)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv) XXX_Size() int {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv.Size(m)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv proto.InternalMessageInfo

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv) GetConfig() *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv) GetState() *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State {
	if m != nil {
		return m.State
	}
	return nil
}

type Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_Config struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_Config) Reset() {
	*m = Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_Config{}
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_Config) String() string {
	return proto.CompactTextString(m)
}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_Config) ProtoMessage() {}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 1, 0, 1, 0, 2, 0, 0}
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_Config.Unmarshal(m, b)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_Config.Marshal(b, m, deterministic)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_Config.Merge(m, src)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_Config) XXX_Size() int {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_Config.Size(m)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_Config proto.InternalMessageInfo

type Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State struct {
	Oui                  *ywrapper.StringValue `protobuf:"bytes,9779901,opt,name=oui,proto3" json:"oui,omitempty"`
	OuiSubtype           *ywrapper.StringValue `protobuf:"bytes,145039116,opt,name=oui_subtype,json=ouiSubtype,proto3" json:"oui_subtype,omitempty"`
	Type                 *ywrapper.IntValue    `protobuf:"bytes,502958044,opt,name=type,proto3" json:"type,omitempty"`
	Value                *ywrapper.BytesValue  `protobuf:"bytes,39320215,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State) Reset() {
	*m = Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State{}
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State) String() string {
	return proto.CompactTextString(m)
}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State) ProtoMessage() {}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 1, 0, 1, 0, 2, 0, 1}
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State.Unmarshal(m, b)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State.Marshal(b, m, deterministic)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State.Merge(m, src)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State) XXX_Size() int {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State.Size(m)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State proto.InternalMessageInfo

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State) GetOui() *ywrapper.StringValue {
	if m != nil {
		return m.Oui
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State) GetOuiSubtype() *ywrapper.StringValue {
	if m != nil {
		return m.OuiSubtype
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State) GetType() *ywrapper.IntValue {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State) GetValue() *ywrapper.BytesValue {
	if m != nil {
		return m.Value
	}
	return nil
}

type Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey struct {
	Type                 int64                                                        `protobuf:"zigzag64,1,opt,name=type,proto3" json:"type,omitempty"`
	Oui                  string                                                       `protobuf:"bytes,2,opt,name=oui,proto3" json:"oui,omitempty"`
	OuiSubtype           string                                                       `protobuf:"bytes,3,opt,name=oui_subtype,json=ouiSubtype,proto3" json:"oui_subtype,omitempty"`
	Tlv                  *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv `protobuf:"bytes,4,opt,name=tlv,proto3" json:"tlv,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                     `json:"-"`
	XXX_unrecognized     []byte                                                       `json:"-"`
	XXX_sizecache        int32                                                        `json:"-"`
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey) Reset() {
	*m = Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey{}
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey) String() string {
	return proto.CompactTextString(m)
}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey) ProtoMessage() {}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 1, 0, 1, 0, 2, 1}
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey.Unmarshal(m, b)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey.Marshal(b, m, deterministic)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey.Merge(m, src)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey) XXX_Size() int {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey.Size(m)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey proto.InternalMessageInfo

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey) GetOui() string {
	if m != nil {
		return m.Oui
	}
	return ""
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey) GetOuiSubtype() string {
	if m != nil {
		return m.OuiSubtype
	}
	return ""
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey) GetTlv() *Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv {
	if m != nil {
		return m.Tlv
	}
	return nil
}

type Lldp_Interfaces_Interface_Neighbors_Neighbor_State struct {
	Age                   *ywrapper.UintValue               `protobuf:"bytes,247861060,opt,name=age,proto3" json:"age,omitempty"`
	ChassisId             *ywrapper.StringValue             `protobuf:"bytes,484827801,opt,name=chassis_id,json=chassisId,proto3" json:"chassis_id,omitempty"`
	ChassisIdType         enums.OpenconfigLldpChassisIdType `protobuf:"varint,365523046,opt,name=chassis_id_type,json=chassisIdType,proto3,enum=openconfig.enums.OpenconfigLldpChassisIdType" json:"chassis_id_type,omitempty"`
	Id                    *ywrapper.StringValue             `protobuf:"bytes,51116368,opt,name=id,proto3" json:"id,omitempty"`
	LastUpdate            *ywrapper.IntValue                `protobuf:"bytes,49325695,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	ManagementAddress     *ywrapper.StringValue             `protobuf:"bytes,403768661,opt,name=management_address,json=managementAddress,proto3" json:"management_address,omitempty"`
	ManagementAddressType *ywrapper.StringValue             `protobuf:"bytes,358938546,opt,name=management_address_type,json=managementAddressType,proto3" json:"management_address_type,omitempty"`
	PortDescription       *ywrapper.StringValue             `protobuf:"bytes,173204743,opt,name=port_description,json=portDescription,proto3" json:"port_description,omitempty"`
	PortId                *ywrapper.StringValue             `protobuf:"bytes,61629116,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	PortIdType            enums.OpenconfigLldpPortIdType    `protobuf:"varint,359632977,opt,name=port_id_type,json=portIdType,proto3,enum=openconfig.enums.OpenconfigLldpPortIdType" json:"port_id_type,omitempty"`
	SystemDescription     *ywrapper.StringValue             `protobuf:"bytes,533250205,opt,name=system_description,json=systemDescription,proto3" json:"system_description,omitempty"`
	SystemName            *ywrapper.StringValue             `protobuf:"bytes,324316296,opt,name=system_name,json=systemName,proto3" json:"system_name,omitempty"`
	Ttl                   *ywrapper.UintValue               `protobuf:"bytes,295076649,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                          `json:"-"`
	XXX_unrecognized      []byte                            `json:"-"`
	XXX_sizecache         int32                             `json:"-"`
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_State) Reset() {
	*m = Lldp_Interfaces_Interface_Neighbors_Neighbor_State{}
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_State) String() string {
	return proto.CompactTextString(m)
}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_State) ProtoMessage() {}
func (*Lldp_Interfaces_Interface_Neighbors_Neighbor_State) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 1, 0, 1, 0, 3}
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_State.Unmarshal(m, b)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_State.Marshal(b, m, deterministic)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_State.Merge(m, src)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_State) XXX_Size() int {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_State.Size(m)
}
func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_State) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_State.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_Neighbor_State proto.InternalMessageInfo

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_State) GetAge() *ywrapper.UintValue {
	if m != nil {
		return m.Age
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_State) GetChassisId() *ywrapper.StringValue {
	if m != nil {
		return m.ChassisId
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_State) GetChassisIdType() enums.OpenconfigLldpChassisIdType {
	if m != nil {
		return m.ChassisIdType
	}
	return enums.OpenconfigLldpChassisIdType_OPENCONFIGLLDPCHASSISIDTYPE_UNSET
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_State) GetId() *ywrapper.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_State) GetLastUpdate() *ywrapper.IntValue {
	if m != nil {
		return m.LastUpdate
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_State) GetManagementAddress() *ywrapper.StringValue {
	if m != nil {
		return m.ManagementAddress
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_State) GetManagementAddressType() *ywrapper.StringValue {
	if m != nil {
		return m.ManagementAddressType
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_State) GetPortDescription() *ywrapper.StringValue {
	if m != nil {
		return m.PortDescription
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_State) GetPortId() *ywrapper.StringValue {
	if m != nil {
		return m.PortId
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_State) GetPortIdType() enums.OpenconfigLldpPortIdType {
	if m != nil {
		return m.PortIdType
	}
	return enums.OpenconfigLldpPortIdType_OPENCONFIGLLDPPORTIDTYPE_UNSET
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_State) GetSystemDescription() *ywrapper.StringValue {
	if m != nil {
		return m.SystemDescription
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_State) GetSystemName() *ywrapper.StringValue {
	if m != nil {
		return m.SystemName
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_Neighbors_Neighbor_State) GetTtl() *ywrapper.UintValue {
	if m != nil {
		return m.Ttl
	}
	return nil
}

type Lldp_Interfaces_Interface_Neighbors_NeighborKey struct {
	Id                   string                                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Neighbor             *Lldp_Interfaces_Interface_Neighbors_Neighbor `protobuf:"bytes,2,opt,name=neighbor,proto3" json:"neighbor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *Lldp_Interfaces_Interface_Neighbors_NeighborKey) Reset() {
	*m = Lldp_Interfaces_Interface_Neighbors_NeighborKey{}
}
func (m *Lldp_Interfaces_Interface_Neighbors_NeighborKey) String() string {
	return proto.CompactTextString(m)
}
func (*Lldp_Interfaces_Interface_Neighbors_NeighborKey) ProtoMessage() {}
func (*Lldp_Interfaces_Interface_Neighbors_NeighborKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 1, 0, 1, 1}
}

func (m *Lldp_Interfaces_Interface_Neighbors_NeighborKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_NeighborKey.Unmarshal(m, b)
}
func (m *Lldp_Interfaces_Interface_Neighbors_NeighborKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_NeighborKey.Marshal(b, m, deterministic)
}
func (m *Lldp_Interfaces_Interface_Neighbors_NeighborKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_NeighborKey.Merge(m, src)
}
func (m *Lldp_Interfaces_Interface_Neighbors_NeighborKey) XXX_Size() int {
	return xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_NeighborKey.Size(m)
}
func (m *Lldp_Interfaces_Interface_Neighbors_NeighborKey) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_NeighborKey.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_Interfaces_Interface_Neighbors_NeighborKey proto.InternalMessageInfo

func (m *Lldp_Interfaces_Interface_Neighbors_NeighborKey) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Lldp_Interfaces_Interface_Neighbors_NeighborKey) GetNeighbor() *Lldp_Interfaces_Interface_Neighbors_Neighbor {
	if m != nil {
		return m.Neighbor
	}
	return nil
}

type Lldp_Interfaces_Interface_State struct {
	Counters             *Lldp_Interfaces_Interface_State_Counters `protobuf:"bytes,244414513,opt,name=counters,proto3" json:"counters,omitempty"`
	Enabled              *ywrapper.BoolValue                       `protobuf:"bytes,397120021,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Name                 *ywrapper.StringValue                     `protobuf:"bytes,157893331,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *Lldp_Interfaces_Interface_State) Reset()         { *m = Lldp_Interfaces_Interface_State{} }
func (m *Lldp_Interfaces_Interface_State) String() string { return proto.CompactTextString(m) }
func (*Lldp_Interfaces_Interface_State) ProtoMessage()    {}
func (*Lldp_Interfaces_Interface_State) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 1, 0, 2}
}

func (m *Lldp_Interfaces_Interface_State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_Interfaces_Interface_State.Unmarshal(m, b)
}
func (m *Lldp_Interfaces_Interface_State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_Interfaces_Interface_State.Marshal(b, m, deterministic)
}
func (m *Lldp_Interfaces_Interface_State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_Interfaces_Interface_State.Merge(m, src)
}
func (m *Lldp_Interfaces_Interface_State) XXX_Size() int {
	return xxx_messageInfo_Lldp_Interfaces_Interface_State.Size(m)
}
func (m *Lldp_Interfaces_Interface_State) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_Interfaces_Interface_State.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_Interfaces_Interface_State proto.InternalMessageInfo

func (m *Lldp_Interfaces_Interface_State) GetCounters() *Lldp_Interfaces_Interface_State_Counters {
	if m != nil {
		return m.Counters
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_State) GetEnabled() *ywrapper.BoolValue {
	if m != nil {
		return m.Enabled
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_State) GetName() *ywrapper.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

type Lldp_Interfaces_Interface_State_Counters struct {
	FrameDiscard         *ywrapper.UintValue   `protobuf:"bytes,259584578,opt,name=frame_discard,json=frameDiscard,proto3" json:"frame_discard,omitempty"`
	FrameErrorIn         *ywrapper.UintValue   `protobuf:"bytes,212424674,opt,name=frame_error_in,json=frameErrorIn,proto3" json:"frame_error_in,omitempty"`
	FrameErrorOut        *ywrapper.UintValue   `protobuf:"bytes,462379421,opt,name=frame_error_out,json=frameErrorOut,proto3" json:"frame_error_out,omitempty"`
	FrameIn              *ywrapper.UintValue   `protobuf:"bytes,521280761,opt,name=frame_in,json=frameIn,proto3" json:"frame_in,omitempty"`
	FrameOut             *ywrapper.UintValue   `protobuf:"bytes,125657400,opt,name=frame_out,json=frameOut,proto3" json:"frame_out,omitempty"`
	LastClear            *ywrapper.StringValue `protobuf:"bytes,456126716,opt,name=last_clear,json=lastClear,proto3" json:"last_clear,omitempty"`
	TlvDiscard           *ywrapper.UintValue   `protobuf:"bytes,93038727,opt,name=tlv_discard,json=tlvDiscard,proto3" json:"tlv_discard,omitempty"`
	TlvUnknown           *ywrapper.UintValue   `protobuf:"bytes,437428095,opt,name=tlv_unknown,json=tlvUnknown,proto3" json:"tlv_unknown,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Lldp_Interfaces_Interface_State_Counters) Reset() {
	*m = Lldp_Interfaces_Interface_State_Counters{}
}
func (m *Lldp_Interfaces_Interface_State_Counters) String() string { return proto.CompactTextString(m) }
func (*Lldp_Interfaces_Interface_State_Counters) ProtoMessage()    {}
func (*Lldp_Interfaces_Interface_State_Counters) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 1, 0, 2, 0}
}

func (m *Lldp_Interfaces_Interface_State_Counters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_Interfaces_Interface_State_Counters.Unmarshal(m, b)
}
func (m *Lldp_Interfaces_Interface_State_Counters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_Interfaces_Interface_State_Counters.Marshal(b, m, deterministic)
}
func (m *Lldp_Interfaces_Interface_State_Counters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_Interfaces_Interface_State_Counters.Merge(m, src)
}
func (m *Lldp_Interfaces_Interface_State_Counters) XXX_Size() int {
	return xxx_messageInfo_Lldp_Interfaces_Interface_State_Counters.Size(m)
}
func (m *Lldp_Interfaces_Interface_State_Counters) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_Interfaces_Interface_State_Counters.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_Interfaces_Interface_State_Counters proto.InternalMessageInfo

func (m *Lldp_Interfaces_Interface_State_Counters) GetFrameDiscard() *ywrapper.UintValue {
	if m != nil {
		return m.FrameDiscard
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_State_Counters) GetFrameErrorIn() *ywrapper.UintValue {
	if m != nil {
		return m.FrameErrorIn
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_State_Counters) GetFrameErrorOut() *ywrapper.UintValue {
	if m != nil {
		return m.FrameErrorOut
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_State_Counters) GetFrameIn() *ywrapper.UintValue {
	if m != nil {
		return m.FrameIn
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_State_Counters) GetFrameOut() *ywrapper.UintValue {
	if m != nil {
		return m.FrameOut
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_State_Counters) GetLastClear() *ywrapper.StringValue {
	if m != nil {
		return m.LastClear
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_State_Counters) GetTlvDiscard() *ywrapper.UintValue {
	if m != nil {
		return m.TlvDiscard
	}
	return nil
}

func (m *Lldp_Interfaces_Interface_State_Counters) GetTlvUnknown() *ywrapper.UintValue {
	if m != nil {
		return m.TlvUnknown
	}
	return nil
}

type Lldp_Interfaces_InterfaceKey struct {
	Name                 string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Interface            *Lldp_Interfaces_Interface `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Lldp_Interfaces_InterfaceKey) Reset()         { *m = Lldp_Interfaces_InterfaceKey{} }
func (m *Lldp_Interfaces_InterfaceKey) String() string { return proto.CompactTextString(m) }
func (*Lldp_Interfaces_InterfaceKey) ProtoMessage()    {}
func (*Lldp_Interfaces_InterfaceKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 1, 1}
}

func (m *Lldp_Interfaces_InterfaceKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_Interfaces_InterfaceKey.Unmarshal(m, b)
}
func (m *Lldp_Interfaces_InterfaceKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_Interfaces_InterfaceKey.Marshal(b, m, deterministic)
}
func (m *Lldp_Interfaces_InterfaceKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_Interfaces_InterfaceKey.Merge(m, src)
}
func (m *Lldp_Interfaces_InterfaceKey) XXX_Size() int {
	return xxx_messageInfo_Lldp_Interfaces_InterfaceKey.Size(m)
}
func (m *Lldp_Interfaces_InterfaceKey) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_Interfaces_InterfaceKey.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_Interfaces_InterfaceKey proto.InternalMessageInfo

func (m *Lldp_Interfaces_InterfaceKey) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Lldp_Interfaces_InterfaceKey) GetInterface() *Lldp_Interfaces_Interface {
	if m != nil {
		return m.Interface
	}
	return nil
}

type Lldp_State struct {
	ChassisId                *ywrapper.StringValue              `protobuf:"bytes,222899705,opt,name=chassis_id,json=chassisId,proto3" json:"chassis_id,omitempty"`
	ChassisIdType            enums.OpenconfigLldpChassisIdType  `protobuf:"varint,26731590,opt,name=chassis_id_type,json=chassisIdType,proto3,enum=openconfig.enums.OpenconfigLldpChassisIdType" json:"chassis_id_type,omitempty"`
	Counters                 *Lldp_State_Counters               `protobuf:"bytes,510522208,opt,name=counters,proto3" json:"counters,omitempty"`
	Enabled                  *ywrapper.BoolValue                `protobuf:"bytes,154847898,opt,name=enabled,proto3" json:"enabled,omitempty"`
	HelloTimer               *ywrapper.UintValue                `protobuf:"bytes,504444337,opt,name=hello_timer,json=helloTimer,proto3" json:"hello_timer,omitempty"`
	SuppressTlvAdvertisement []enums.OpenconfigLldpTypesLLDPTLV `protobuf:"varint,4804491,rep,packed,name=suppress_tlv_advertisement,json=suppressTlvAdvertisement,proto3,enum=openconfig.enums.OpenconfigLldpTypesLLDPTLV" json:"suppress_tlv_advertisement,omitempty"`
	SystemDescription        *ywrapper.StringValue              `protobuf:"bytes,194456445,opt,name=system_description,json=systemDescription,proto3" json:"system_description,omitempty"`
	SystemName               *ywrapper.StringValue              `protobuf:"bytes,444378600,opt,name=system_name,json=systemName,proto3" json:"system_name,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                           `json:"-"`
	XXX_unrecognized         []byte                             `json:"-"`
	XXX_sizecache            int32                              `json:"-"`
}

func (m *Lldp_State) Reset()         { *m = Lldp_State{} }
func (m *Lldp_State) String() string { return proto.CompactTextString(m) }
func (*Lldp_State) ProtoMessage()    {}
func (*Lldp_State) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 2}
}

func (m *Lldp_State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_State.Unmarshal(m, b)
}
func (m *Lldp_State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_State.Marshal(b, m, deterministic)
}
func (m *Lldp_State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_State.Merge(m, src)
}
func (m *Lldp_State) XXX_Size() int {
	return xxx_messageInfo_Lldp_State.Size(m)
}
func (m *Lldp_State) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_State.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_State proto.InternalMessageInfo

func (m *Lldp_State) GetChassisId() *ywrapper.StringValue {
	if m != nil {
		return m.ChassisId
	}
	return nil
}

func (m *Lldp_State) GetChassisIdType() enums.OpenconfigLldpChassisIdType {
	if m != nil {
		return m.ChassisIdType
	}
	return enums.OpenconfigLldpChassisIdType_OPENCONFIGLLDPCHASSISIDTYPE_UNSET
}

func (m *Lldp_State) GetCounters() *Lldp_State_Counters {
	if m != nil {
		return m.Counters
	}
	return nil
}

func (m *Lldp_State) GetEnabled() *ywrapper.BoolValue {
	if m != nil {
		return m.Enabled
	}
	return nil
}

func (m *Lldp_State) GetHelloTimer() *ywrapper.UintValue {
	if m != nil {
		return m.HelloTimer
	}
	return nil
}

func (m *Lldp_State) GetSuppressTlvAdvertisement() []enums.OpenconfigLldpTypesLLDPTLV {
	if m != nil {
		return m.SuppressTlvAdvertisement
	}
	return nil
}

func (m *Lldp_State) GetSystemDescription() *ywrapper.StringValue {
	if m != nil {
		return m.SystemDescription
	}
	return nil
}

func (m *Lldp_State) GetSystemName() *ywrapper.StringValue {
	if m != nil {
		return m.SystemName
	}
	return nil
}

type Lldp_State_Counters struct {
	EntriesAgedOut       *ywrapper.UintValue   `protobuf:"bytes,502981410,opt,name=entries_aged_out,json=entriesAgedOut,proto3" json:"entries_aged_out,omitempty"`
	FrameDiscard         *ywrapper.UintValue   `protobuf:"bytes,519798735,opt,name=frame_discard,json=frameDiscard,proto3" json:"frame_discard,omitempty"`
	FrameErrorIn         *ywrapper.UintValue   `protobuf:"bytes,122178213,opt,name=frame_error_in,json=frameErrorIn,proto3" json:"frame_error_in,omitempty"`
	FrameIn              *ywrapper.UintValue   `protobuf:"bytes,341206510,opt,name=frame_in,json=frameIn,proto3" json:"frame_in,omitempty"`
	FrameOut             *ywrapper.UintValue   `protobuf:"bytes,487587569,opt,name=frame_out,json=frameOut,proto3" json:"frame_out,omitempty"`
	LastClear            *ywrapper.StringValue `protobuf:"bytes,310897635,opt,name=last_clear,json=lastClear,proto3" json:"last_clear,omitempty"`
	TlvAccepted          *ywrapper.UintValue   `protobuf:"bytes,497028407,opt,name=tlv_accepted,json=tlvAccepted,proto3" json:"tlv_accepted,omitempty"`
	TlvDiscard           *ywrapper.UintValue   `protobuf:"bytes,409814106,opt,name=tlv_discard,json=tlvDiscard,proto3" json:"tlv_discard,omitempty"`
	TlvUnknown           *ywrapper.UintValue   `protobuf:"bytes,356843514,opt,name=tlv_unknown,json=tlvUnknown,proto3" json:"tlv_unknown,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Lldp_State_Counters) Reset()         { *m = Lldp_State_Counters{} }
func (m *Lldp_State_Counters) String() string { return proto.CompactTextString(m) }
func (*Lldp_State_Counters) ProtoMessage()    {}
func (*Lldp_State_Counters) Descriptor() ([]byte, []int) {
	return fileDescriptor_bffef4577fe65fbd, []int{0, 2, 0}
}

func (m *Lldp_State_Counters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lldp_State_Counters.Unmarshal(m, b)
}
func (m *Lldp_State_Counters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lldp_State_Counters.Marshal(b, m, deterministic)
}
func (m *Lldp_State_Counters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lldp_State_Counters.Merge(m, src)
}
func (m *Lldp_State_Counters) XXX_Size() int {
	return xxx_messageInfo_Lldp_State_Counters.Size(m)
}
func (m *Lldp_State_Counters) XXX_DiscardUnknown() {
	xxx_messageInfo_Lldp_State_Counters.DiscardUnknown(m)
}

var xxx_messageInfo_Lldp_State_Counters proto.InternalMessageInfo

func (m *Lldp_State_Counters) GetEntriesAgedOut() *ywrapper.UintValue {
	if m != nil {
		return m.EntriesAgedOut
	}
	return nil
}

func (m *Lldp_State_Counters) GetFrameDiscard() *ywrapper.UintValue {
	if m != nil {
		return m.FrameDiscard
	}
	return nil
}

func (m *Lldp_State_Counters) GetFrameErrorIn() *ywrapper.UintValue {
	if m != nil {
		return m.FrameErrorIn
	}
	return nil
}

func (m *Lldp_State_Counters) GetFrameIn() *ywrapper.UintValue {
	if m != nil {
		return m.FrameIn
	}
	return nil
}

func (m *Lldp_State_Counters) GetFrameOut() *ywrapper.UintValue {
	if m != nil {
		return m.FrameOut
	}
	return nil
}

func (m *Lldp_State_Counters) GetLastClear() *ywrapper.StringValue {
	if m != nil {
		return m.LastClear
	}
	return nil
}

func (m *Lldp_State_Counters) GetTlvAccepted() *ywrapper.UintValue {
	if m != nil {
		return m.TlvAccepted
	}
	return nil
}

func (m *Lldp_State_Counters) GetTlvDiscard() *ywrapper.UintValue {
	if m != nil {
		return m.TlvDiscard
	}
	return nil
}

func (m *Lldp_State_Counters) GetTlvUnknown() *ywrapper.UintValue {
	if m != nil {
		return m.TlvUnknown
	}
	return nil
}

func init() {
	proto.RegisterType((*Lldp)(nil), "openconfig.openconfig_lldp.Lldp")
	proto.RegisterType((*Lldp_Config)(nil), "openconfig.openconfig_lldp.Lldp.Config")
	proto.RegisterType((*Lldp_Interfaces)(nil), "openconfig.openconfig_lldp.Lldp.Interfaces")
	proto.RegisterType((*Lldp_Interfaces_Interface)(nil), "openconfig.openconfig_lldp.Lldp.Interfaces.Interface")
	proto.RegisterType((*Lldp_Interfaces_Interface_Config)(nil), "openconfig.openconfig_lldp.Lldp.Interfaces.Interface.Config")
	proto.RegisterType((*Lldp_Interfaces_Interface_Neighbors)(nil), "openconfig.openconfig_lldp.Lldp.Interfaces.Interface.Neighbors")
	proto.RegisterType((*Lldp_Interfaces_Interface_Neighbors_Neighbor)(nil), "openconfig.openconfig_lldp.Lldp.Interfaces.Interface.Neighbors.Neighbor")
	proto.RegisterType((*Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities)(nil), "openconfig.openconfig_lldp.Lldp.Interfaces.Interface.Neighbors.Neighbor.Capabilities")
	proto.RegisterType((*Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability)(nil), "openconfig.openconfig_lldp.Lldp.Interfaces.Interface.Neighbors.Neighbor.Capabilities.Capability")
	proto.RegisterType((*Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_Config)(nil), "openconfig.openconfig_lldp.Lldp.Interfaces.Interface.Neighbors.Neighbor.Capabilities.Capability.Config")
	proto.RegisterType((*Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_Capability_State)(nil), "openconfig.openconfig_lldp.Lldp.Interfaces.Interface.Neighbors.Neighbor.Capabilities.Capability.State")
	proto.RegisterType((*Lldp_Interfaces_Interface_Neighbors_Neighbor_Capabilities_CapabilityKey)(nil), "openconfig.openconfig_lldp.Lldp.Interfaces.Interface.Neighbors.Neighbor.Capabilities.CapabilityKey")
	proto.RegisterType((*Lldp_Interfaces_Interface_Neighbors_Neighbor_Config)(nil), "openconfig.openconfig_lldp.Lldp.Interfaces.Interface.Neighbors.Neighbor.Config")
	proto.RegisterType((*Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs)(nil), "openconfig.openconfig_lldp.Lldp.Interfaces.Interface.Neighbors.Neighbor.CustomTlvs")
	proto.RegisterType((*Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv)(nil), "openconfig.openconfig_lldp.Lldp.Interfaces.Interface.Neighbors.Neighbor.CustomTlvs.Tlv")
	proto.RegisterType((*Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_Config)(nil), "openconfig.openconfig_lldp.Lldp.Interfaces.Interface.Neighbors.Neighbor.CustomTlvs.Tlv.Config")
	proto.RegisterType((*Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_Tlv_State)(nil), "openconfig.openconfig_lldp.Lldp.Interfaces.Interface.Neighbors.Neighbor.CustomTlvs.Tlv.State")
	proto.RegisterType((*Lldp_Interfaces_Interface_Neighbors_Neighbor_CustomTlvs_TlvKey)(nil), "openconfig.openconfig_lldp.Lldp.Interfaces.Interface.Neighbors.Neighbor.CustomTlvs.TlvKey")
	proto.RegisterType((*Lldp_Interfaces_Interface_Neighbors_Neighbor_State)(nil), "openconfig.openconfig_lldp.Lldp.Interfaces.Interface.Neighbors.Neighbor.State")
	proto.RegisterType((*Lldp_Interfaces_Interface_Neighbors_NeighborKey)(nil), "openconfig.openconfig_lldp.Lldp.Interfaces.Interface.Neighbors.NeighborKey")
	proto.RegisterType((*Lldp_Interfaces_Interface_State)(nil), "openconfig.openconfig_lldp.Lldp.Interfaces.Interface.State")
	proto.RegisterType((*Lldp_Interfaces_Interface_State_Counters)(nil), "openconfig.openconfig_lldp.Lldp.Interfaces.Interface.State.Counters")
	proto.RegisterType((*Lldp_Interfaces_InterfaceKey)(nil), "openconfig.openconfig_lldp.Lldp.Interfaces.InterfaceKey")
	proto.RegisterType((*Lldp_State)(nil), "openconfig.openconfig_lldp.Lldp.State")
	proto.RegisterType((*Lldp_State_Counters)(nil), "openconfig.openconfig_lldp.Lldp.State.Counters")
}

func init() {
	proto.RegisterFile("ocproto/openconfig/openconfig_lldp/openconfig_lldp.proto", fileDescriptor_bffef4577fe65fbd)
}

var fileDescriptor_bffef4577fe65fbd = []byte{
	// 2604 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x5a, 0x7f, 0x70, 0x14, 0xd5,
	0x1d, 0x9f, 0x4d, 0x20, 0x24, 0x2f, 0x09, 0xe8, 0xf3, 0x07, 0xdb, 0x53, 0x10, 0x51, 0xf9, 0xa1,
	0x5c, 0xc2, 0x84, 0x82, 0xfc, 0x10, 0xf5, 0x5d, 0x82, 0x72, 0x12, 0x09, 0xb3, 0x39, 0xc2, 0xd0,
	0x11, 0xce, 0xcb, 0xed, 0x12, 0x16, 0x36, 0xbb, 0xc7, 0xed, 0xde, 0xe1, 0xc1, 0xd8, 0xa1, 0x4f,
	0x81, 0x8c, 0xd2, 0x5a, 0x07, 0x52, 0x04, 0x44, 0x2a, 0x9a, 0xa9, 0xad, 0x1d, 0x68, 0xda, 0xa1,
	0xd0, 0x96, 0x1f, 0xca, 0xaf, 0x11, 0xa5, 0x15, 0x95, 0xd6, 0x82, 0x4c, 0xd5, 0xea, 0x58, 0xa6,
	0x0c, 0x04, 0xb0, 0x28, 0xb4, 0x20, 0x9d, 0x7d, 0x6f, 0x6f, 0x7f, 0x5c, 0xee, 0xf6, 0x72, 0x97,
	0xcb, 0x3f, 0x37, 0x6f, 0xf7, 0xf6, 0x7d, 0x3e, 0x9f, 0xef, 0xdb, 0xef, 0x8f, 0xdd, 0xef, 0x3e,
	0x30, 0x51, 0x09, 0x47, 0xa2, 0x8a, 0xa6, 0x54, 0x2b, 0x11, 0x41, 0x0e, 0x2b, 0xf2, 0x02, 0xb1,
	0xc5, 0x36, 0x0c, 0x4a, 0x12, 0x1f, 0x49, 0x3d, 0xae, 0x22, 0x13, 0xa0, 0xc7, 0x3a, 0x5d, 0x95,
	0x72, 0x85, 0x67, 0x62, 0x8b, 0xa8, 0x2d, 0x8c, 0x35, 0x57, 0x85, 0x95, 0x56, 0x3b, 0x70, 0xa2,
	0x45, 0xd1, 0xaa, 0x29, 0x5d, 0x62, 0x69, 0x34, 0x14, 0x89, 0x08, 0x51, 0x73, 0x40, 0x51, 0x3d,
	0x63, 0xb3, 0xcf, 0x14, 0x9e, 0xd2, 0xc8, 0x8f, 0x31, 0xe3, 0x76, 0xdb, 0x65, 0x82, 0x1c, 0x6b,
	0x55, 0xe9, 0x2f, 0xfd, 0x77, 0xf8, 0x01, 0x0e, 0xf4, 0xab, 0x97, 0xf8, 0x08, 0x0c, 0x80, 0x12,
	0x7a, 0x11, 0xbb, 0xf3, 0xda, 0xe1, 0xe3, 0xcc, 0x30, 0x66, 0x54, 0x79, 0xcd, 0xc8, 0xaa, 0xcc,
	0x36, 0x54, 0xe9, 0xb3, 0xaa, 0x6a, 0xc9, 0x09, 0xdf, 0x20, 0x8c, 0x2a, 0xaa, 0xc9, 0x5a, 0xd0,
	0x2b, 0x38, 0x03, 0x0b, 0x36, 0x03, 0x20, 0xca, 0x9a, 0x10, 0x5d, 0x10, 0x0a, 0x0b, 0x2a, 0xdb,
	0xbe, 0x7b, 0x3e, 0xc1, 0xbd, 0x2f, 0x2b, 0xae, 0xdf, 0x9c, 0xe4, 0xbb, 0x09, 0xa3, 0x1b, 0x28,
	0xb6, 0x85, 0xc4, 0xd9, 0x50, 0x61, 0x03, 0xe8, 0xaf, 0x6a, 0x21, 0x4d, 0x60, 0x4f, 0xbf, 0xbd,
	0x8b, 0x23, 0xf8, 0x23, 0xb2, 0xe2, 0x37, 0xea, 0x13, 0x7c, 0x03, 0x31, 0x2a, 0xa7, 0xd0, 0x04,
	0x80, 0xa3, 0x38, 0x9e, 0x7f, 0xf4, 0x07, 0x25, 0xd4, 0x30, 0x18, 0x00, 0x20, 0xbc, 0x30, 0xa4,
	0xaa, 0xa2, 0x1a, 0x14, 0x79, 0xf6, 0xe5, 0x1d, 0x5b, 0x2f, 0xd2, 0x95, 0xb9, 0xa5, 0xca, 0xbc,
	0x2f, 0x8d, 0x5a, 0x54, 0x94, 0x5b, 0x9a, 0x42, 0x52, 0x4c, 0xf0, 0x79, 0x30, 0x1a, 0x6c, 0x5f,
	0x87, 0x6a, 0x63, 0xb2, 0x57, 0xe4, 0xb9, 0x32, 0x63, 0xec, 0xe7, 0xe1, 0x32, 0x30, 0xc8, 0x42,
	0x0d, 0x6a, 0x89, 0x88, 0xc0, 0x76, 0x7e, 0x79, 0xf0, 0x27, 0x3a, 0xf4, 0xc0, 0x1a, 0xaf, 0x5d,
	0x3c, 0xbd, 0x55, 0x0d, 0xe6, 0x09, 0x5d, 0x7c, 0x6d, 0x12, 0x27, 0x90, 0x88, 0x08, 0xbe, 0x3b,
	0x30, 0xba, 0x3d, 0x03, 0xa5, 0x57, 0x47, 0xe6, 0x2a, 0xc3, 0xf6, 0xeb, 0xa1, 0x1f, 0x0c, 0x10,
	0xe4, 0x50, 0xb3, 0x24, 0xf0, 0xec, 0x91, 0xcf, 0x8f, 0xd4, 0x10, 0x6b, 0x6e, 0xb2, 0xac, 0xf1,
	0x29, 0x8a, 0x44, 0x6d, 0x19, 0x8c, 0xd1, 0xcd, 0x0e, 0x60, 0x63, 0x1a, 0x97, 0x9c, 0x0f, 0x67,
	0x83, 0xf2, 0x85, 0x82, 0x24, 0x29, 0x41, 0x4d, 0x6c, 0x15, 0xa2, 0x2c, 0xde, 0xfa, 0xd3, 0x73,
	0x4c, 0x2a, 0xde, 0x6c, 0x51, 0xd6, 0x28, 0xde, 0x6d, 0x18, 0xb1, 0x0e, 0x3c, 0x32, 0xd7, 0x4b,
	0xe6, 0x72, 0x80, 0x1c, 0x04, 0xf4, 0x31, 0xdc, 0xc0, 0x00, 0x8f, 0x1a, 0x8b, 0x44, 0xa2, 0x82,
	0xaa, 0x06, 0x35, 0x29, 0x1e, 0x0c, 0xf1, 0x71, 0x21, 0xaa, 0x89, 0xaa, 0xd0, 0x2a, 0xc8, 0x1a,
	0xfb, 0xca, 0x8a, 0xdd, 0x35, 0xc3, 0x8a, 0x47, 0x0d, 0xac, 0x19, 0x93, 0x6d, 0xa1, 0x74, 0x7b,
	0xd5, 0xfa, 0xfa, 0xba, 0x59, 0x81, 0xfa, 0x26, 0xdf, 0xbd, 0x18, 0x8d, 0x74, 0xd0, 0x27, 0x29,
	0xbc, 0x9a, 0x14, 0xf7, 0x3a, 0x28, 0x38, 0x36, 0xf9, 0x5f, 0x40, 0x8a, 0x23, 0xfb, 0x3f, 0x50,
	0x02, 0x50, 0x4d, 0xa8, 0x9a, 0xd0, 0x1a, 0xe4, 0x05, 0x35, 0x1c, 0x15, 0x23, 0x9a, 0xa8, 0xc8,
	0xec, 0xe9, 0x43, 0x7f, 0x3f, 0xe0, 0xea, 0x17, 0xc3, 0x31, 0xba, 0xc3, 0x49, 0x4e, 0x40, 0xbc,
	0x36, 0x10, 0xee, 0x46, 0x7a, 0xae, 0xce, 0x3a, 0x05, 0x9b, 0x40, 0xb9, 0xc1, 0x26, 0x87, 0x5a,
	0x05, 0x76, 0xf5, 0xaa, 0xeb, 0x65, 0x6e, 0x2c, 0xdd, 0x56, 0xd8, 0x60, 0xd1, 0x27, 0x73, 0x80,
	0x1e, 0xcc, 0x0c, 0xb5, 0x0a, 0x9e, 0x4d, 0x53, 0x01, 0xb0, 0x22, 0x0c, 0x26, 0x40, 0x99, 0x19,
	0x4e, 0xec, 0x85, 0xf3, 0x07, 0xfe, 0xc4, 0x0c, 0x2b, 0x1e, 0x55, 0x5e, 0x33, 0x31, 0x87, 0x28,
	0xb5, 0x86, 0x33, 0x84, 0x84, 0x6f, 0x08, 0x46, 0x9e, 0xd4, 0x90, 0xb5, 0x86, 0x9c, 0xc5, 0xe6,
	0xf9, 0x7a, 0x32, 0x28, 0x33, 0xa7, 0xc2, 0xa7, 0xcd, 0x1c, 0xf4, 0xb3, 0x0b, 0x87, 0x2b, 0x89,
	0xa9, 0x0f, 0xe4, 0x25, 0x22, 0x99, 0x97, 0xee, 0xc6, 0xe8, 0xce, 0xcc, 0x42, 0x52, 0x93, 0xd5,
	0x73, 0x0c, 0x28, 0x93, 0x05, 0xb1, 0x65, 0x61, 0xb3, 0x12, 0x55, 0xd9, 0xb3, 0x47, 0x9e, 0xb9,
	0x44, 0x6f, 0xea, 0x43, 0xf9, 0x69, 0x98, 0x99, 0x84, 0xf2, 0x8d, 0xc4, 0xe8, 0x6e, 0x17, 0x19,
	0x26, 0x27, 0x67, 0xd1, 0xc3, 0x44, 0x32, 0xab, 0x1d, 0x58, 0xb5, 0xa1, 0x99, 0xc8, 0x98, 0x92,
	0x9f, 0x0c, 0x9a, 0xea, 0xee, 0xc2, 0x68, 0x98, 0x8b, 0x04, 0x47, 0xfe, 0xdb, 0xcf, 0x98, 0xf9,
	0x2f, 0x68, 0x65, 0x8b, 0x67, 0xaf, 0x3e, 0xfb, 0x35, 0x93, 0x39, 0x5d, 0x8c, 0xc1, 0x68, 0x74,
	0xd6, 0xa5, 0xee, 0x9e, 0x43, 0xe6, 0x80, 0x7e, 0xc4, 0xb7, 0xaf, 0xfe, 0xa5, 0x6d, 0x84, 0x9b,
	0x6f, 0x8f, 0xc6, 0x68, 0x44, 0x76, 0x78, 0xe2, 0xe9, 0x04, 0xd0, 0xf3, 0xe2, 0x18, 0x50, 0x66,
	0xde, 0x01, 0xb8, 0x99, 0x01, 0xa5, 0xc9, 0xb5, 0x65, 0xbf, 0x79, 0xfb, 0x8d, 0x6f, 0xa9, 0x8b,
	0xcf, 0xe8, 0xe5, 0x9d, 0x35, 0x47, 0xba, 0xd7, 0x8f, 0xc5, 0xc8, 0xdb, 0x93, 0xbb, 0x6c, 0x8e,
	0x38, 0x53, 0x92, 0xe7, 0x8d, 0xd1, 0xa0, 0x34, 0x89, 0x05, 0x77, 0x33, 0xa0, 0x22, 0x1c, 0x8a,
	0x84, 0x9a, 0x45, 0x49, 0xd4, 0x44, 0x41, 0x65, 0xbb, 0x7e, 0xb1, 0xe9, 0x24, 0x5d, 0xfa, 0xd9,
	0x85, 0x12, 0x5c, 0x55, 0x6b, 0x23, 0xf0, 0x4d, 0xc5, 0x68, 0x72, 0x4e, 0xd2, 0xab, 0xed, 0xfa,
	0x38, 0x87, 0x5a, 0xf8, 0x1a, 0x63, 0x86, 0xf1, 0xc7, 0x1f, 0xfe, 0x79, 0x11, 0xd1, 0xdd, 0x50,
	0x38, 0xdd, 0x34, 0xb2, 0xef, 0xc7, 0xe8, 0xfb, 0x39, 0x2a, 0x76, 0x06, 0xfb, 0x0e, 0x06, 0x94,
	0x87, 0x63, 0xaa, 0xa6, 0xb4, 0xea, 0x35, 0x46, 0x65, 0x7f, 0xdd, 0xb5, 0x7e, 0x19, 0x91, 0xda,
	0x58, 0x38, 0xa9, 0x04, 0x3e, 0x20, 0xc5, 0x55, 0xdf, 0x03, 0x18, 0x4d, 0xca, 0x51, 0x2e, 0x99,
	0xac, 0x17, 0x27, 0x95, 0x03, 0x61, 0x13, 0x09, 0x6e, 0x61, 0x92, 0x89, 0xa1, 0xed, 0xea, 0x95,
	0x9b, 0x89, 0xe2, 0x99, 0x05, 0x53, 0x4c, 0x73, 0xc5, 0x04, 0x8c, 0xc6, 0xe5, 0x26, 0xd6, 0x91,
	0x3e, 0xd6, 0x01, 0x50, 0x61, 0xf7, 0x2e, 0x78, 0x8c, 0x01, 0xc0, 0xf4, 0x90, 0x04, 0x7b, 0xfc,
	0xf2, 0xef, 0x15, 0x12, 0x7d, 0xe1, 0x3e, 0x71, 0x66, 0xeb, 0x20, 0xa1, 0x47, 0xe5, 0x74, 0x8c,
	0xa6, 0xe5, 0xef, 0xda, 0xd6, 0x41, 0x82, 0xb3, 0xd9, 0xe0, 0xb9, 0xda, 0x1f, 0x00, 0x8b, 0x07,
	0x1e, 0xb7, 0x5c, 0xfe, 0xc4, 0xd1, 0xff, 0x3d, 0x43, 0x63, 0xb5, 0xa5, 0xaf, 0xcd, 0x4b, 0xc6,
	0x42, 0x03, 0x46, 0xf5, 0x05, 0x31, 0x31, 0x35, 0x46, 0xde, 0x37, 0x7d, 0x6d, 0xdb, 0x37, 0xed,
	0x43, 0x89, 0x51, 0x0b, 0xfa, 0xdc, 0x28, 0xea, 0x83, 0x33, 0x31, 0x9a, 0x51, 0x18, 0x9b, 0x1c,
	0xbe, 0x59, 0x9a, 0xac, 0x6c, 0x9e, 0x3f, 0x16, 0x81, 0xfe, 0x84, 0x0a, 0xb6, 0x31, 0x56, 0x91,
	0x3b, 0xfa, 0xfc, 0x0b, 0x0d, 0x99, 0x6b, 0x5c, 0x13, 0x46, 0x8d, 0x05, 0x14, 0xd5, 0xbd, 0x1a,
	0x76, 0x30, 0x46, 0x39, 0xfc, 0xcf, 0x77, 0x5b, 0xcb, 0xc8, 0xdb, 0xc0, 0xa4, 0x1e, 0x3f, 0xe4,
	0x36, 0xce, 0x6d, 0x0c, 0x4c, 0x7b, 0xbc, 0x16, 0xcd, 0x42, 0x3e, 0x7f, 0xbd, 0x3f, 0x30, 0xd7,
	0xd7, 0x88, 0xd1, 0xac, 0x42, 0xaa, 0xb5, 0x15, 0xd7, 0xce, 0x22, 0x50, 0xe9, 0x08, 0x33, 0xf8,
	0x72, 0x52, 0x39, 0xd3, 0x5b, 0xd9, 0x8f, 0x63, 0xf4, 0x58, 0x61, 0x64, 0x5b, 0x82, 0xe1, 0x0a,
	0x67, 0x0a, 0x2a, 0x22, 0xf7, 0xf8, 0xc9, 0xbe, 0xf6, 0x65, 0x47, 0xca, 0xb0, 0x5c, 0xef, 0x72,
	0x39, 0x00, 0x56, 0x6d, 0x80, 0x9d, 0x0c, 0x28, 0xd6, 0xa4, 0x38, 0xbb, 0xef, 0x64, 0xdb, 0x22,
	0x92, 0x17, 0x7f, 0xd0, 0x07, 0x15, 0xa8, 0x2a, 0x20, 0xc5, 0xf5, 0x74, 0xf8, 0x30, 0x46, 0x53,
	0xf3, 0x2e, 0x44, 0xd5, 0x9a, 0x14, 0xe7, 0x74, 0xad, 0x9e, 0xcd, 0x03, 0x40, 0x71, 0x40, 0x8a,
	0xc3, 0xfd, 0x56, 0xe2, 0x5b, 0xb1, 0xe2, 0x9c, 0x44, 0x96, 0x75, 0x7e, 0x1f, 0xc9, 0x4f, 0xa6,
	0xbb, 0x47, 0x31, 0xaa, 0xeb, 0x95, 0x09, 0xa9, 0x69, 0x6e, 0xaf, 0x99, 0xe6, 0xae, 0x1c, 0x59,
	0x35, 0x96, 0xd8, 0x30, 0xaf, 0xaf, 0x6c, 0xa0, 0xd9, 0xed, 0x11, 0x8c, 0x6a, 0x7b, 0x67, 0x42,
	0x86, 0xac, 0xb6, 0xb2, 0x5f, 0x32, 0xab, 0xc5, 0x41, 0xb1, 0x12, 0x13, 0xd9, 0x3d, 0x97, 0x8e,
	0xf7, 0x73, 0x7b, 0xae, 0x7e, 0x0c, 0xa3, 0x47, 0x0b, 0xa0, 0xa4, 0x5a, 0x89, 0x89, 0x9c, 0x4e,
	0x08, 0x7f, 0xcc, 0x80, 0x72, 0x25, 0x26, 0x06, 0xd5, 0x58, 0x33, 0x69, 0x6c, 0xac, 0xd9, 0xbb,
	0x6e, 0x9a, 0x9b, 0x00, 0x0e, 0xa3, 0x86, 0x02, 0x09, 0xf0, 0x1a, 0x9c, 0x1c, 0x50, 0x62, 0x62,
	0x23, 0x1d, 0xc3, 0xa5, 0xa0, 0x1f, 0xd1, 0x71, 0xea, 0x85, 0x7f, 0x77, 0xd1, 0xba, 0x0c, 0x2d,
	0x21, 0xfe, 0x64, 0x73, 0x62, 0x06, 0x46, 0xd3, 0x0b, 0xa1, 0x82, 0xd0, 0x13, 0x42, 0xb8, 0x1c,
	0xf4, 0x8f, 0xeb, 0xd8, 0xec, 0xfa, 0x4b, 0x9f, 0x42, 0x42, 0x7c, 0xb3, 0xad, 0xa6, 0x24, 0x34,
	0x41, 0xa5, 0xd4, 0xf5, 0x18, 0xf9, 0x0b, 0x41, 0x4d, 0xc8, 0x38, 0xca, 0xe9, 0x69, 0x2f, 0x06,
	0x25, 0x34, 0xe2, 0xe1, 0x5c, 0x63, 0x01, 0x74, 0xe3, 0xa1, 0x6f, 0x1a, 0x46, 0xbe, 0xde, 0xb1,
	0xd9, 0x4c, 0x6c, 0xa2, 0x3e, 0xa6, 0x67, 0xd3, 0x32, 0x5f, 0x1d, 0x46, 0xa8, 0x77, 0xc8, 0xa6,
	0x0f, 0xb5, 0x3a, 0x5d, 0xa8, 0x98, 0xe0, 0xf7, 0x7e, 0x9d, 0x32, 0xb9, 0x88, 0x48, 0xf3, 0x2f,
	0x8d, 0x93, 0x39, 0x7d, 0x14, 0xf9, 0x34, 0x6f, 0xbe, 0x55, 0x99, 0x8c, 0x4f, 0x1e, 0x14, 0x87,
	0x5a, 0x04, 0xf6, 0xe0, 0x2b, 0x2f, 0xc5, 0x33, 0xf7, 0xcc, 0x26, 0x63, 0x74, 0x7f, 0x1e, 0x4f,
	0xe2, 0xd5, 0xa1, 0x16, 0x81, 0xd3, 0xe1, 0xe1, 0x72, 0x47, 0xff, 0x72, 0xc3, 0xa1, 0xf5, 0xff,
	0x72, 0xed, 0x53, 0x21, 0x8c, 0x1e, 0xcc, 0x87, 0x2f, 0x7d, 0x9b, 0xf3, 0x55, 0xa6, 0x7b, 0x9f,
	0xf3, 0xab, 0xcf, 0x3a, 0xb6, 0xe5, 0xd5, 0xe7, 0xcc, 0x3d, 0x65, 0xa6, 0x4a, 0x4b, 0xdb, 0x0e,
	0x0d, 0x83, 0x22, 0x91, 0x67, 0x8f, 0x5d, 0xdc, 0xce, 0xba, 0xad, 0xcb, 0x24, 0x8c, 0x26, 0xe4,
	0x43, 0x2e, 0xf2, 0x5c, 0x91, 0xc8, 0xc3, 0x65, 0xa0, 0x5c, 0x0a, 0xa9, 0x5a, 0x30, 0x16, 0xe1,
	0xf5, 0x2a, 0x73, 0xfd, 0xe8, 0xfe, 0xc1, 0x19, 0x33, 0x91, 0x0f, 0xa3, 0x87, 0xf2, 0xa1, 0xd2,
	0x09, 0xbc, 0x94, 0x80, 0x03, 0xfa, 0xc1, 0x6c, 0x32, 0x86, 0x6b, 0x19, 0x00, 0x5b, 0x43, 0x72,
	0xa8, 0x85, 0x34, 0x30, 0x83, 0x21, 0x9e, 0x8f, 0x0a, 0xaa, 0xca, 0xfe, 0xf5, 0xb9, 0x83, 0x6f,
	0xb9, 0xba, 0x82, 0x1f, 0xa3, 0x47, 0xf2, 0xd1, 0x61, 0x71, 0x79, 0x0d, 0x2e, 0xee, 0x46, 0xeb,
	0x1c, 0xa2, 0xa7, 0x74, 0xd7, 0x18, 0xdc, 0x5d, 0x15, 0x75, 0x91, 0xdf, 0x76, 0xad, 0x7d, 0xd3,
	0x55, 0x5a, 0xee, 0xef, 0x06, 0x99, 0xa4, 0x51, 0x97, 0xb8, 0xa5, 0x9b, 0x3e, 0xe2, 0x1a, 0x6b,
	0x18, 0x70, 0x43, 0x44, 0x89, 0x6a, 0x8e, 0x56, 0xef, 0xea, 0x77, 0xdf, 0xe3, 0xdc, 0xb4, 0xe5,
	0xfe, 0x70, 0x42, 0xb5, 0xe9, 0x44, 0x8e, 0x76, 0xf0, 0x20, 0xfd, 0x8c, 0xbd, 0x19, 0xbc, 0x04,
	0x0c, 0x20, 0x6a, 0x44, 0x9e, 0xdd, 0x7d, 0xa8, 0x73, 0x88, 0x9b, 0x88, 0x07, 0x31, 0x9a, 0x92,
	0xb7, 0x08, 0x91, 0xe7, 0x4a, 0xf4, 0x81, 0x9f, 0x87, 0xed, 0x0c, 0xa8, 0x30, 0x38, 0xe9, 0xad,
	0xf9, 0xe0, 0xe7, 0x7b, 0xdf, 0xa4, 0xd1, 0x7b, 0x6f, 0xb6, 0xe8, 0x9d, 0x45, 0x20, 0x48, 0xe8,
	0xd6, 0x62, 0xf4, 0x70, 0x2f, 0xe4, 0xd0, 0x9b, 0x04, 0x22, 0x26, 0x20, 0xf1, 0xe9, 0x34, 0x6d,
	0xf8, 0xcd, 0x3f, 0x7a, 0xed, 0xbb, 0x3e, 0xf1, 0xe9, 0x9e, 0x75, 0xeb, 0x7f, 0xe8, 0xec, 0xd6,
	0xb7, 0x9d, 0xf8, 0x70, 0xa3, 0xab, 0x9a, 0x7c, 0x23, 0x3d, 0x43, 0x57, 0x1f, 0x0a, 0xa0, 0x58,
	0xd3, 0x24, 0xf6, 0x97, 0xab, 0x4e, 0xae, 0x61, 0x0a, 0x5f, 0x52, 0x34, 0x4d, 0xe2, 0x74, 0x7c,
	0xcf, 0x2e, 0x06, 0x94, 0xdb, 0xda, 0x9e, 0xb0, 0x96, 0x64, 0x50, 0x86, 0xd4, 0xe8, 0x71, 0x18,
	0x8d, 0xcd, 0x0d, 0xdc, 0xc8, 0x90, 0xbc, 0xad, 0x3d, 0x4b, 0x5f, 0xce, 0xa6, 0x17, 0xaa, 0x0e,
	0xdb, 0xba, 0xac, 0x2b, 0x41, 0xb2, 0xfa, 0xbe, 0xc8, 0x80, 0xd2, 0xb0, 0x12, 0xd3, 0xa7, 0xa9,
	0x6c, 0xe7, 0xf9, 0x43, 0x1a, 0xe1, 0xac, 0xeb, 0x45, 0x87, 0xbd, 0xaa, 0xd6, 0x80, 0xcb, 0xd6,
	0x09, 0x37, 0xca, 0x92, 0x71, 0x35, 0x67, 0xca, 0x80, 0xf3, 0xad, 0x36, 0x44, 0xfb, 0xeb, 0xdb,
	0xf6, 0xb8, 0xf4, 0xda, 0xef, 0xc3, 0x68, 0x54, 0x56, 0x86, 0x6e, 0xcd, 0x85, 0x26, 0xe3, 0x0d,
	0xfd, 0xa3, 0x95, 0x1d, 0x33, 0xdc, 0xfc, 0x72, 0x14, 0x46, 0xf7, 0x64, 0x45, 0xb7, 0x35, 0x03,
	0xb6, 0x0f, 0x00, 0xa5, 0x49, 0xe3, 0xe1, 0x52, 0x50, 0xb9, 0x20, 0x1a, 0x6a, 0x15, 0x82, 0xbc,
	0xa8, 0x86, 0x43, 0x51, 0x9e, 0xdd, 0xff, 0xe5, 0x17, 0xcb, 0xf3, 0xf6, 0x46, 0xe7, 0x5a, 0x55,
	0x13, 0x64, 0xaf, 0x81, 0xcc, 0x55, 0x90, 0xc3, 0x3a, 0x7a, 0x04, 0x13, 0x60, 0x20, 0x25, 0x16,
	0xa2, 0x51, 0x25, 0x1a, 0x14, 0x65, 0xf6, 0x9f, 0xdb, 0x3b, 0x84, 0xcc, 0xcc, 0x53, 0x30, 0x9a,
	0x98, 0x2b, 0x33, 0x81, 0xf6, 0x8a, 0xb2, 0x41, 0x3d, 0x4d, 0x3f, 0xf4, 0xcb, 0xf0, 0x69, 0x30,
	0xc8, 0x4e, 0xad, 0xc4, 0x34, 0x76, 0xf3, 0xef, 0xf6, 0x9c, 0x72, 0x09, 0xc2, 0x2c, 0xed, 0x60,
	0x17, 0x72, 0x25, 0xa6, 0x71, 0x95, 0x16, 0x7b, 0x43, 0x4c, 0x83, 0x22, 0x28, 0xa5, 0xf4, 0xa2,
	0xcc, 0x5e, 0xf9, 0xc3, 0x3b, 0x97, 0x5d, 0x78, 0xc7, 0x63, 0x54, 0x93, 0x2b, 0xaf, 0x28, 0x73,
	0x03, 0xc8, 0xc8, 0x2f, 0xc3, 0xc5, 0xa0, 0x8c, 0x52, 0xe9, 0x36, 0xee, 0xda, 0x7f, 0x69, 0x4a,
	0x66, 0xaa, 0x2c, 0x4d, 0xe4, 0xb4, 0x54, 0xba, 0x71, 0xd4, 0x16, 0xdd, 0xae, 0x25, 0x80, 0x3c,
	0xc7, 0x04, 0xc3, 0x92, 0x10, 0x8a, 0xb2, 0x57, 0x3f, 0xdf, 0x77, 0xc2, 0x35, 0x9d, 0x66, 0xf9,
	0x22, 0x90, 0x42, 0x48, 0x1e, 0x97, 0x08, 0x32, 0x57, 0xa6, 0x8f, 0x6b, 0xf5, 0x21, 0x5c, 0x02,
	0xca, 0x35, 0x29, 0x6e, 0xfa, 0xee, 0xea, 0x0f, 0xb6, 0x8d, 0xc9, 0x6c, 0xe1, 0x44, 0x8c, 0xc6,
	0xf7, 0x9c, 0x50, 0x93, 0xe2, 0xa6, 0xe7, 0x02, 0x4d, 0x8a, 0x27, 0xfd, 0x36, 0x4a, 0x29, 0x63,
	0xf2, 0x62, 0x59, 0x59, 0x2a, 0xb3, 0xd7, 0xf7, 0xbe, 0x7b, 0x8c, 0x29, 0x24, 0xa7, 0x01, 0x4c,
	0x38, 0x67, 0xd3, 0xb1, 0x67, 0x13, 0x03, 0x2a, 0xec, 0x1f, 0x6c, 0xe1, 0x04, 0x5b, 0xf3, 0xae,
	0xcc, 0xf6, 0xb5, 0x3a, 0x7d, 0x16, 0xb7, 0xda, 0x6a, 0x8d, 0xf6, 0x2f, 0xc7, 0x34, 0x6f, 0x8f,
	0xcf, 0x2b, 0x87, 0xda, 0xbf, 0x09, 0xff, 0xc6, 0x7c, 0x47, 0xe2, 0x1c, 0x6f, 0x2f, 0x57, 0x3e,
	0x79, 0x7d, 0x91, 0x9b, 0x03, 0x7c, 0x0f, 0xa3, 0x5b, 0x6d, 0xbb, 0x39, 0x32, 0xbc, 0x94, 0x3c,
	0xd5, 0xfd, 0x9d, 0xe4, 0xf0, 0x3b, 0x9f, 0x56, 0xe4, 0xf3, 0x4a, 0x32, 0x14, 0xa3, 0xdb, 0xd2,
	0x13, 0xa6, 0x7d, 0xd5, 0x58, 0x68, 0x2b, 0x39, 0x9f, 0x7d, 0xb5, 0xd3, 0xf8, 0x98, 0x5a, 0xdd,
	0xb3, 0xbd, 0x2a, 0x56, 0x79, 0xb1, 0xf6, 0x65, 0x64, 0xac, 0x24, 0xd3, 0xad, 0x4a, 0xb2, 0xb1,
	0xfd, 0x8c, 0x3f, 0x73, 0x21, 0xb9, 0x15, 0xa3, 0x9b, 0xec, 0x58, 0xdd, 0x6a, 0x46, 0xc0, 0xb9,
	0xc5, 0xa3, 0xf3, 0xcc, 0xc1, 0xf3, 0x2e, 0xde, 0x69, 0x6d, 0x7f, 0xa1, 0x70, 0x99, 0x76, 0x78,
	0xbc, 0xe4, 0xbe, 0xc3, 0xe3, 0xf9, 0x2d, 0x1d, 0x45, 0x79, 0xec, 0xf0, 0xb0, 0x3e, 0x11, 0x1b,
	0xcf, 0x49, 0xf9, 0x6c, 0xf0, 0x58, 0x94, 0xf6, 0xc9, 0xf2, 0xda, 0xdf, 0x4e, 0x3d, 0xe1, 0xe6,
	0x7a, 0x77, 0x62, 0x34, 0xd4, 0x41, 0x9d, 0xcf, 0xf6, 0x8e, 0xd3, 0x9f, 0x5c, 0xfc, 0xa8, 0x87,
	0xbb, 0x8b, 0x5c, 0x1f, 0x04, 0x3d, 0x5d, 0x25, 0xb6, 0x82, 0xbc, 0x18, 0xdc, 0x20, 0xc8, 0x5a,
	0x54, 0x14, 0xd4, 0x60, 0xa8, 0x45, 0xe0, 0x49, 0xe6, 0xde, 0x7a, 0xf8, 0x4c, 0x97, 0xcb, 0x6d,
	0xb4, 0x1e, 0x00, 0x52, 0xf2, 0x89, 0x01, 0xe4, 0xd5, 0x81, 0x48, 0xb2, 0x1e, 0x68, 0x9c, 0x41,
	0x2d, 0x02, 0xaf, 0xa7, 0xec, 0x70, 0x6a, 0xf5, 0x7f, 0xff, 0xfa, 0xd9, 0x6f, 0x5d, 0x98, 0xee,
	0xc1, 0x68, 0x78, 0x5a, 0x26, 0xb7, 0x4a, 0xcf, 0x77, 0xab, 0xf4, 0x1d, 0xed, 0xaf, 0x4e, 0xce,
	0x4c, 0x32, 0x02, 0xa3, 0xbb, 0x5c, 0x48, 0x32, 0x14, 0xf5, 0x80, 0xad, 0xaa, 0x9e, 0x7b, 0xef,
	0xc4, 0x56, 0x17, 0x2b, 0x86, 0x61, 0x34, 0xc4, 0x85, 0xc0, 0x5e, 0x40, 0xe7, 0xd8, 0x0b, 0xe8,
	0x85, 0x6b, 0xfb, 0x4e, 0xbb, 0xc0, 0xa6, 0x3a, 0x95, 0x6b, 0xb1, 0x7c, 0xc2, 0x51, 0x2c, 0xbf,
	0xf8, 0x78, 0xcb, 0xba, 0x1e, 0x6e, 0x48, 0xea, 0x51, 0x5d, 0x7c, 0x12, 0x54, 0x90, 0x30, 0x0d,
	0x87, 0x85, 0x88, 0x26, 0xf0, 0xec, 0xce, 0x8d, 0x2b, 0xce, 0xba, 0x28, 0xb7, 0xb6, 0xdd, 0xa4,
	0x29, 0x48, 0x49, 0x10, 0x4e, 0xaf, 0x7b, 0xc8, 0x38, 0x80, 0xf3, 0x9c, 0x95, 0xf7, 0x64, 0xdb,
	0x8e, 0x03, 0x2e, 0x04, 0xd6, 0x6e, 0x96, 0x1e, 0x56, 0xd9, 0x79, 0xce, 0x2a, 0xfb, 0xdf, 0xeb,
	0x6b, 0x7f, 0x95, 0x2f, 0x7c, 0x9a, 0x82, 0xda, 0x5c, 0x42, 0x36, 0x53, 0x8e, 0xfb, 0x7f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xda, 0x55, 0xa8, 0x63, 0x2e, 0x2a, 0x00, 0x00,
}
